language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.4

env:
  - DB=mysql
services:
  - mysql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test CODECLIMATE_REPO_TOKEN=e0c5c8579049a9f13fbb0e7972054eca3091ecf48f821f0d59cf25036671e28e bundle exec rake

before_script:
  - mysql -e 'create database mymusic_test;'
branches:
  only:
    - master
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: e0c5c8579049a9f13fbb0e7972054eca3091ecf48f821f0d59cf25036671e28e
